reporting:
  print: summary
  reports:
    - lcov
  dir: ./coverage
  watermarks:
    statements: [50, 80]
    lines: [50, 80]
    functions: [50, 80]
    branches: [50, 80]
    report-config:
      json: {file: coverage-final.json}
      text: {file: null, maxCols: 0}
      text-lcov: {file: lcov.info}

check:
  global:
    statements: 100
    lines: 100
    branches: 100
    functions: 100
    excludes: []
  each:
    statements: 100
    lines: 100
    # HACK: transpile path not taken
    branches: 80
    functions: 100
    excludes: []
