vile:
  ignore:
    - .test
    - ruby/.bundle/**
    - test/fixtures/**
    - test/**/*.js
    - .ackrc
    - appveyor.yml
    - bin
    - .bundle
    - circle.yml
    - haskell/dist/**
    - haskell/.cabal-sandbox/**
    - coverage
    - public
    - db
    - vendor
    - tmp
    - .git
    - node_modules
    - .log
    - .keep
    - tags
    - .brakeman.yml
    - .ctags
    - .editorconfig
    - .env
    - .eslintignore
    - .eslintrc
    - .gitignore
    - .npmrc
    - .reek
    - .rspec
    - .rubocop.yml
    - .ruby-version
    - .vile.yml
    - LICENSE

rubycritic:
  allow:
    - ruby
  config:
    method_count: 10
    complexity: 80
    churn: 20
    rating: "A"

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs:
      - src
      - typings
      - node_modules
      - coverage
      - haskell
      - ruby
      - tmp
    ignore_deps:
      - mocha
      - babel-cli
      - coffee-script
      - npm-check-updates
      - istanbul
      - release-it
      - typescript
      - wrench
      - pryjs
      - shelljs
      - "vile-*"

rubcocop:
  config: .rubocop.yml

bundler-audit:
  config:
    update_db: true

coverage:
  config:
    path: coverage/lcov.info

eslint:
  config: .eslintrc
  ignore: .eslintignore

coffeelint:
  config: coffeelint.json

hlint:
  allow:
    - haskell/src
    - haskell/test
